<?xml version="1.0"?>
<package format="3">
  <name>exotica_ddp_solver</name>
  <version>6.2.0</version>
  <description>DDP Solvers for EXOTica (Analytic, Control-Limited, Feasibility-Driven variants)</description>
  <maintainer email="opensource@wolfgangmerkt.com">Wolfgang Merkt</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <depend>exotica_core</depend>
  <depend>exotica_python</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
