<?xml version="1.0"?>
<package format="3">
  <name>exotica_levenberg_marquardt_solver</name>
  <version>6.2.0</version>
  <description>Levenberg-Marquardt Solver for EXOTica</description>
  <maintainer email="opensource@wolfgangmerkt.com">Wolfgang Merkt</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>exotica_core</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
