#!/usr/bin/env python

import pyexotica as exo
import exotica_ompl_solver_py as ompl
from pyexotica.publish_trajectory import publish_trajectory

exo.Setup.init_ros()
solver = exo.Setup.load_solver(
    '{exotica_examples}/resources/configs/example_ompl_projections.xml')

solution = solver.solve()

publish_trajectory(solution, 3.0, solver.get_problem())
