#!/usr/bin/env python

import signal
import pyexotica as exo
from numpy import array
from pyexotica.publish_trajectory import *
from time import sleep

import exotica_scipy_solver

exo.Setup.init_ros()
tmp_solver = exo.Setup.load_solver(
    '{exotica_ifopt_solver}/resources/ifopt_ik_constrained.xml')
problem = tmp_solver.get_problem()

solver = exotica_scipy_solver.SciPyEndPoseSolver(problem)

dt = 0.002
t = 0.0
q = array([0.0]*7)
print('Publishing IK')
signal.signal(signal.SIGINT, sig_int_handler)
# problem = solver.get_problem()
while True:
    try:
        problem.start_state = q
        problem.start_time = t
        q = solver.solve()
        publish_pose(q, problem, t)
        sleep(dt)
        t = (t+dt) % 7.0
    except KeyboardInterrupt:
        break
