#!/usr/bin/env python
import pyexotica as exo
from numpy import array
from pyexotica.publish_trajectory import *
from time import sleep
import signal

exo.Setup.init_ros()
solver = exo.Setup.load_solver(
    '{exotica_ifopt_solver}/resources/ifopt_traj_constrained.xml')
problem = solver.get_problem()

for t in range(0, problem.T):
    if float(t) * problem.tau < 0.8:
        problem.set_rho_eq('Position', 0.0, t)
    else:
        problem.set_rho_eq('Position', 1, t)

t = 0.0
q = array([0.0] * 7)
print('Solving...')
signal.signal(signal.SIGINT, sig_int_handler)
solution = solver.solve()
print('Publishing...')
publish_trajectory(solution, problem.T * problem.tau, problem)
